uncle(X, prince_william).
grandparent(prince_philip, prince_william).
child(princess_beatrice, sarah_ferguson).
child(princess_beatrice, prince_edward).
grandmother(queen_elizabethII, princess_eugenie).
married(X, kate_middleton).
husband(X, kate_middleton).
son(X, prince_philip).
sister(X, prince_andrew).
niece(X, prince_charles).
wife(queen_elizabethII, prince_philip).
son(prince_william, prince_philip).
nephew(X, prince_edward).
aunt(X, prince_william).
daughter(X, prince_philip).
wife(X, prince_edward).
husband(X, princess_anne).
sibling(princess_anne, prince_edward).
grandchild(X, prince_philip).
grandfather(X, prince_charles).
