child(X, molly_weasley).
wife(hermione_granger, harry_potter).
boyfriend(X, victoire_weasley).
girlfriend(roxanne_weasley, teddy_lupin).
son(X, audrey_weasley).
aunt(X, dominique_weasley).
uncle(X, lily_luna_potter).
grandchild(X, arthur_weasley).
grandson(james_sirius_potter, X).
granddaughter(lucy_weasley, james_potter).
daughter(X, fleur_delacour).
father(X, hugo_weasley).
mother(molly_weasley, molly_weasley_ii).
husband(X, nymphadora_tonks).
brother(X, scorpius_malfoy).
sister(rose_weasley, hugo_weasley).
sibling(X, albus_severus_potter).
grandfather(X, louis_weasley).
grandmother(X, fred_weasley_ii).
grandparent(X, james_sirius_potter).
niece(X, angelina_johnson).
nephew(X, fred_weasley).
nephew(X, percy_weasley).
